name: build

on: push

jobs:
  build:
    permissions:
      contents: write
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Unit test
        run: go test ./... -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: |
          mkdir dist
          
          # update version
          sed -i 's/__VERSION__/${{ github.ref_name }}/g' serverstat.go
          
          # linux
          GOOS=linux GOARCH=amd64 go build -o dist/serverstat
          zip --junk-paths dist/serverstat-linux64-${{ github.ref_name }}.zip dist/serverstat
          
          # TODO: enable once working properly
          # windows
          #GOOS=windows GOARCH=amd64 go build -o dist/serverstat.exe
          #zip --junk-paths dist/serverstat-win64-${{ github.ref_name }}.zip dist/serverstat.exe
          
          ls dist

      - name: Test build
        run: ./dist/serverstat --help

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/*.zip
